[main]
ip = "baystellardynasty.aternos.me:45295"
login = "offline"
username = "AFK_Bot_1"

[appvars]
showlinks = false

[autoafk]
enabled = true
delay = 10
command = "/ping"

[reconnectionservice]
enabled = true
delay = 10
interval = 300
