[Main]
# 伺服器資訊
serverip=baystellardynasty.aternos.me:45295
type=offline
username=AFK_Bot_1

[AppVars]
# 停用不必要的模組以節省效能
showlinks=false

[AutoAFK]
enabled=true
delay=10
# 防踢防閒置命令（自動在遊戲內發送指令或動作）
command=/ping

[ReconnectionService]
enabled=true
delay=10
interval=300
